### ISSUE TITLE
INFO1213 R10 Assignment 5

### ISSUE THREAD

**Issue by madmoney99** [haomateach/webdev#44]
I am continually getting this error on my blog assignment.  I have tried reinstalling mongo, mongoDB and mongoose through NPM, no change.

The blog site sucessfully writes a new blog page, saves it to MongoDB and I can continue navigating.  The crash happens when I try to go directly to one of the blog pages ....posts/5fae253610191c0004271e82 as an example.  That generates the crash. 

I have googled a number of these errors and don't see anything similar.  I have gone back and re-watched the videos multiple times and I don't see anything I'm doing differently from Angela's steps.

```
F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\helpers\promiseOrCallback.js:19
            throw error;
            ^

TypeError: Cannot read property 'title' of undefined
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\app.js:68:19
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\model.js:4846:16
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\model.js:4846:16
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\helpers\promiseOrCallback.js:16:11     
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\model.js:4869:21
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\query.js:4383:18
    at model.Query.<anonymous> (F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\query.js:2101:5)
    at model.Query._wrappedThunk [as _findOne] (F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\kareem\index.js:369:33
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Function instance at:
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\model.js:4848:13
    at F:\Personal\School\aFall 2020\INFO1213\GitHub Repo\info1213a5\node_modules\mongoose\lib\helpers\promiseOrCallback.js:16:11     
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:79:11)```

**Comment by madmoney99** [comment]
I solved it, I ran the heroku logs --tail until I narrowed the problem down.  Had to do with some formatting and paths in the header/footer ejs files.
